# Паттерны каллбэков кнопок меню объявлений
(ALL_INFO_MESSAGES_PATTERN, ALL_CATEGORYS_PATTERN,

 TITLE_SEARCH_PATTERN, CATEGORY_SEARCH_PATTERN, ADD_INFO_MESSAGE_PATTERN,

 ADD_MESSAGE_CATEGORY_PATTERN, SEND_MESSAGE_PATTERN,

 UPDATE_MESSAGE_PATTERN, DELETE_MESSAGE_PATTERN,

 YES_DELETE_PATTERN, NO_DELETE_PATTERN,
 # Отмена Назад
 BACK_PATTERN, CANCEL_PATTERN, SKIP_PATTERN, SEND_VOTE_PATTERN
 ) = range(15)

# состояния converations

# поиск по заголовкам и категориям состояния
(TITLE_SEARCH_STATE, CHOOSE_MESSAGE_STATE,
 CATEGORY_SEARCH_STATE, CHOOSE_CATEGORY_STATE,
 # создание объявления
 TITLE_ENTER_STATE, CATEGORY_ENTER_STATE,
 CONTENT_ENTER_STATE,
 # создание категории
 ADD_CATEGORY_ENTER_STATE,
 # изменение объявления
 UPDATE_CATEGORY_STATE, UPDATE_TITLE_STATE, UPDATE_CONTENT_STATE,
  # Состояния создания ссылки
 CHOOSE_UCHP_LINK_STATE, CHOOSE_COURSE_LINK_STATE, CHOOSE_GROUP_LINK_STATE
 ) = range(1, 15)
